# Generated by Django 5.0.4 on 2024-05-02 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('time_stamp', models.CharField(default=datetime.datetime(2024, 5, 2, 16, 42, 38, 498671), max_length=100)),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvotes', to='base.ip')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvotes', to='base.ip')),
            ],
        ),
    ]
