# Generated by Django 5.0.4 on 2024-05-13 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=1000)),
                ('text', models.CharField(max_length=1000)),
                ('time_stamp', models.CharField(default=datetime.datetime(2024, 5, 13, 12, 48, 58, 671978), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=16)),
                ('instagram', models.CharField(default='', max_length=30)),
                ('text', models.CharField(max_length=500)),
                ('time_stamp', models.CharField(default=datetime.datetime(2024, 5, 13, 12, 48, 58, 672439), max_length=100)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='base.comment')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvotes', to='base.ip')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvotes', to='base.ip')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='comment_downvotes', to='base.ip'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='comment_upvotes', to='base.ip'),
        ),
    ]
