# Generated by Django 5.0.4 on 2024-05-04 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='username',
            field=models.CharField(default='anonymous', max_length=1000),
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 4, 17, 40, 4, 827130), max_length=100),
        ),
    ]
