# Generated by Django 5.0.4 on 2024-05-06 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_confession_username_alter_confession_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=1000)),
                ('text', models.CharField(max_length=1000)),
                ('time_stamp', models.CharField(default=datetime.datetime(2024, 5, 6, 17, 56, 44, 360012), max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 6, 17, 56, 44, 360270), max_length=100),
        ),
        migrations.AddField(
            model_name='confession',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to='base.comment'),
        ),
    ]
