# Generated by Django 5.0.4 on 2024-05-13 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_comment_time_stamp_alter_confession_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 13, 13, 13, 7, 423818), max_length=100),
        ),
        migrations.AlterField(
            model_name='confession',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to='base.userkey'),
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 13, 13, 13, 7, 424282), max_length=100),
        ),
        migrations.AlterField(
            model_name='confession',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='base.userkey'),
        ),
    ]
