# Generated by Django 5.0.4 on 2024-05-13 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_comment_time_stamp_alter_confession_downvotes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IP',
        ),
        migrations.AlterField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='comment_downvotes', to='base.userkey'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 13, 13, 36, 55, 306338), max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='comment_upvotes', to='base.userkey'),
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 13, 13, 36, 55, 306796), max_length=100),
        ),
    ]
