# Generated by Django 5.0.4 on 2024-05-13 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_ip_alter_comment_downvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='downvotes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 13, 13, 39, 34, 937540), max_length=100),
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 13, 13, 39, 34, 937650), max_length=100),
        ),
    ]
