# Generated by Django 5.0.4 on 2024-05-06 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_comment_upvotes_alter_comment_time_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='comment_downvotes', to='base.ip'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 6, 17, 58, 49, 532504), max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='comment_upvotes', to='base.ip'),
        ),
        migrations.AlterField(
            model_name='confession',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='base.comment'),
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 6, 17, 58, 49, 533273), max_length=100),
        ),
    ]
