# Generated by Django 5.0.4 on 2024-05-08 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment_downvotes_alter_comment_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 8, 17, 56, 27, 168624), max_length=100),
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 8, 17, 56, 27, 169854), max_length=100),
        ),
    ]
