# Generated by Django 5.0.4 on 2024-05-12 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_comment_time_stamp_alter_confession_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 12, 10, 23, 29, 568142), max_length=100),
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 12, 10, 23, 29, 568657), max_length=100),
        ),
    ]
