# Generated by Django 5.0.4 on 2024-05-12 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_comment_time_stamp_alter_confession_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='instagram',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 12, 11, 46, 52, 185808), max_length=100),
        ),
        migrations.AlterField(
            model_name='confession',
            name='time_stamp',
            field=models.CharField(default=datetime.datetime(2024, 5, 12, 11, 46, 52, 186305), max_length=100),
        ),
    ]
